#!/bin/bash

# AxOS hooks runner
# This script is used to update parts of the AxOS system.
# Usage: axos-hooks-runner <hook name>
# Avaiable hooks:
#   os-release:-------------------- replace the content of /etc/os-release with the latest content
#   lsb-release:------------------- same as os-release but for /etc/lsb-release
#   reload-theme:------------------ reload the users theme and config with the latest AxOS look (avaiable only after axskel update)
#   bash-prompt-replace:----------- Replace the bash prompt of the user with 'λ ~'.
#   reload-plymouth: -------------- Set the boot animation to the default AxOS theme
#   full:-------------------------- Do Everything
# WARNING: DO NOT EXECUTE UNLESS YOU KNOW WHAT YOU ARE DOING
# Author: Ardox
# Date: 2024
# This file is part of the AxOS project.
## Copyright (C) 2024 Ardox

if [ -f /etc/axos-version ]; then
    version=$(cat /etc/axos-version)
else
    version="24.08" # Because the new version system is above 24.08
fi

ps1_replace() {
	local file=/etc/skel/.bashrc
	echo 'PS1="\[\e[00;34m\]λ \W \[\e[0m\] "' | tee $file > /dev/null
	cp $file $HOME
}

plymouth_theme_replace() {
    plymouth-set-default-theme axos
    mkinitcpio -p linux
}

main() {
    local hookname="$1"

    case "$hookname" in
        bash-prompt-replace) ps1_replace;;
        reload-plymouth) plymouth_theme_replace ;;
        full)        ps1_replace
                     plymouth_theme_replace
                     ;;

	*)  echo "invalid input"
		;;
    esac
}

main "$@"
